config/routes.rb
Rails.application.routes.draw do
  resources :dashboards, path: 'dashboard'
  resources :requests
  resources :sessions, path: 'login'

  root to: 'requests#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include AASM

  validates :email, uniqueness: true, presence: true

  aasm do # default column: aasm_state
    state :noaws, :initial => true
    state :aws

    event :add do
      transitions :to => :aws
    end

    event :reset do
      transitions :to => :noaws
    end
  end

  def randompin
    self.update_column(:pin, rand(1000..9999))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user

  def authenticated?
    redirect_to sessions_url, alert: "Please login, and you'll be sent to the page you tried to access." if current_user.nil?
  end

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find_by(id: session[:user_id]) 
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticated?

  def index
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  def index
    redirect_to dashboards_path if current_user
  end

  def create
    user = User.new(email: params[:email])

    if user.save
      user.randompin
      #AmazonAccount.create(user)
      RequestMailer.delay.confirmation(user)
      redirect_to sessions_path, notice: "An e-mail has been sent to you containing your PIN"
    else
      flash.now[:alerts] = user.errors.full_messages
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authenticated?, except: [:index, :create]

  def index
    redirect_to dashboards_path unless current_user.nil?
  end

  def create
    user = User.find_by(email: params[:email].downcase, pin: params[:pin])
    if user 
      if user.noaws?
        aa = AmazonAccount.new
        aa.create(user)
      end
      session[:user_id] = user.id
      redirect_to dashboards_path, notice: "Welcome! Future employer or co-worker!"
    else
      flash[:alert] = "Incorrect email address or pin"
      render "index"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to sessions_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboards/index.html.haml
%h1.uk-text-center
  Dashboard
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    Goal
  The goal of this site is to showcase my talents in AWS and Ruby on Rails.  Please note that the site itself is not meant to showcase any design skills.  The sites purpose is to display what I can do.
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    Contact Me
  My e-mail address:
  %strong
    = mail_to "joelhill-ische.com", "joel@joelhill-ische.com"
  %br
  My phone number:
  %strong
    (952) 200-3092
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    Resume
  = link_to "docx", "https://s3.amazonaws.com/joelhillischeresumes/AWS/JoelHill-IscheResume.docx"
  = link_to "pdf", "https://s3.amazonaws.com/joelhillischeresumes/AWS/JoelHill-IscheResume.pdf"
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    Architecture
  %dl.uk-description-list-line
    %dt
      Ruby on Rails
    %dd
      This language was choosen because it was easy to set up and simple to administer for a simple application.
    %dt
      Nginx
    %dd
      In an effort to determine which web server to use between Apache and Nginx I decided on Nginx since it was light and easy to set up.
    %dt
      EC2
    %dd
      I used EC2 to create a compute node as opposed to Elastic Bean Stalk to be able to granularly create a environment to serve up Ruby on Rails.  Lambda since it only supports Python, and Node.js.
    %dt
      S3
    %dd
      I use S3 to store the resume, images, and diagrams.
    %dt
      My AMI
    %dd
      This allows me to set up the perfect instance so I can use Auto Scaling.
    %dt
      RDB (PostgreSQL)
    %dd
      PostgreSQL allows for transactional changes which can easily be rolledback if an error occurs.
    %dt
      ELB
    %dd
      I use Multi-AZ deployments set over 2 subnets.
    %dt
      Auto Scaling
    %dd
      In case where there is a higher load I want to make sure that there is another server to handle the load.  So I set up triggers when the servers hit a higher threshold.  Now I do not believe to be the case since this site simply does one thing, but I meant the feature to showcase my ability to configure AS.
    %dt
      IAM
    %dd
      To add a power user (not root) for main administration of the account.  To add a username automatically based on the users e-mail address.  We also add a password and add the new user to a read-only account.
    %dt
      Subnet
    %dd
      Subnet (Public) - I set up two subnets in two AZs both with Auto Scaling turned on in case of one AZ going down.
    %dt
      SES 
    %dd
      I use this to send e-mail of the username / PIN.  I first send the request to a delayed_job queue then I have set up to login to the SES SMTP server to send the e-mail.
    %dt
      GitLab vs. BitBucket vs. GitHub vs. Amazon
    %dd
      It was free.  I am trying to conserve pricing and I found their interface to be easy to use.  I am not as familiar with AWS CodeCommit and if that is what I want to implement.
    %dt
    %dd
      I followed this for naming
      AWS Region ( 2 char ) = US, EU, VA, CA etc
      AWS AZ = EAST, WEST etc
      %br
      Environment Code (1 Char)  = P-Production , Q-QA, T-testing, D-Development etc
      %br
      OS Type (1 Char)= L -Linux, W-Windows etc
      %br
      Tier (1 Char)= W-Web, A-App, C-Cache, D-DB etc
      %br
      Application Code ( 4 Chars) = A001
    %dt
      New Code
    %dd
      So I had a custom AMI that I created that was deployed by a scaling group.  The only problem was that I wanted to make sure I had the latest code on boot time.  So I could log into every instance when one started and do a git reset --hard and a git pull origin master but then what happens if auto-scaling wants to create an instance when I am not around.  So I decided to add something to the user-data portion of the custom AMI.
      %pre.code
        = preserve do
          :escaped
            #!/bin/bash
            apt-get -y install awscli
            mkdir /home/ubuntu/.ssh/
            aws s3 cp s3://joelhillischeresumes/Key/ec2 /home/ubuntu/.ssh/
            chmod 600 /home/ubuntu/.ssh/ec2
            eval `ssh-agent -s`
            ssh-add /home/ubuntu/.ssh/ec2
            ssh-keyscan -t rsa gitlab.com > .ssh/known_hosts
            cd /home/ubuntu/resume && git reset --hard && git pull origin master
            chown -R ubuntu:ubuntu /home/ubuntu/resume/
            su - ubuntu -c "cd /home/ubuntu/resume && bin/delayed_job stop && bin/delayed_job start" 
    %dt
      Possible Future Improvements
    %dd
      Some possible future improvements include
      %ul
        %li
          Authenticating using oath
        %li
          Tuning CloudWatch to send me billing metrics to determine what I am spending
        %li
          Turning on access logs in ELB to see where traffic is coming from
        %li
          Adding CloudFront for static resumes
        %li
          Setting up either CodeDeploy, capistrano, or ansible to push git changes out (CodeDeploy does not integrate as well with Gitlab as Github)
        %li
          = mail_to "joel@joelhill-ische.com", "If you have any suggestions please feel free to reach out."
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    Diagram
  = link_to "Google Drawing Document", "https://docs.google.com/drawings/d/1pAXKxqtfe39lZzaDRSYBL4NfCEPuFSgh1XkgNoxkwJ4/edit?usp=sharing"
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    AWS Username / Password (Generated via sdk)
  Console:
  = link_to "Amazon Access", "https://joelhill-ische.signin.aws.amazon.com/console"
  %br
  .uk-text-bold
    Username
  = "#{current_user.amazon_username}"
  %br
  .uk-text-bold
    Password
  = "#{current_user.amazon_password}"
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    AWS Access Keys (Generated via sdk)
  .uk-text-bold
    Access Key
  = "#{current_user.access_key_id}"
  %br
  .uk-text-bold
    Secret Access Key
  = "#{current_user.secret_access_key}"
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    Pictures of paper diagram (this is how I started to think about this)
  = link_to "Image (hosted by S3 of course)", "https://s3.amazonaws.com/joelhillischeresumes/AWS/diagram.of.aws.environment.jpg"
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    Ruby on Rails code
  = link_to "Gitlab", "https://gitlab.com/joelhillische/resume/tree/master"
%br
.uk-panel.uk-panel-box.uk-panel-header
  .uk-panel-title
    Other Articles read
  = link_to "http://harish11g.blogspot.com/2015/06/best-practices-tips-on-amazon-web-services-security-groups-aws-security-managed-services.html", "http://harish11g.blogspot.com/2015/06/best-practices-tips-on-amazon-web-services-security-groups-aws-security-managed-services.html"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Resume
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .uk-container.uk-container-center
      - if flash[:notice] 
        .uk-alert.uk-alert-success
          = "#{flash[:notice]}"
        %br
      - if flash[:alerts]
        - flash[:alerts].each do |alert|
          .uk-alert.uk-alert-danger
            = "#{alert}"
          %br
      - if flash[:alert]
        .uk-alert.uk-alert-danger
          = "#{flash[:alert]}"
        %br
      - if current_user
        .uk-text-center
          .uk-panel.uk-panel-box
            = "Welcome #{current_user.email}"
            = link_to "Log out", session_path(current_user), method: "delete"
      = yield

app/views/requests/index.html.haml
%h1
  Request PIN
.uk-form
  =form_tag @request do
    %fieldset
      .uk-form-row
        = text_field_tag :email, nil, placeholder: "Your email address"
      .uk-form-row
        = submit_tag "Request access", class: "uk-button"
      .uk-form-row
        = link_to "If you already have an account with a pin you can login here", "http://aws.joelhill-ische.com/login"
  %br
  .uk-panel.uk-panel-box
    Note: You will receive an e-mail address with your username (email address) and PIN.
  %br
  .uk-panel.uk-panel-box
    As just a preview here is the GitLab repository that you may be interested in
    = link_to "(click here)", "https://gitlab.com/joelhillische/resume/"